#Custom Archetype
!setname 0x1f7 Divine Implement
!setname 0x1f8 Fantasia
!setname 0x1f9 Reimu the Eternal Shrine Maiden
!setname 0x1fa Onmyō
!setname 0x1fb Pandaemonium
!setname 0x1fc Mystikrios
!setname 0x1fd Kyrio
!setname 0x1fe Piscera
!setname 0x2f0 Umbriazic
